// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Najmodavac.AppDbContext;

namespace Najmodavac.Migrations
{
    [DbContext(typeof(SmjestajDbContext))]
    [Migration("20200724234112_NazivTipSmjestaja")]
    partial class NazivTipSmjestaja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Najmodavac.Models.NazivSmjestaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("NazivViewTipSmjestajaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NazivViewTipSmjestajaId");

                    b.ToTable("NaziviSmjestaja");
                });

            modelBuilder.Entity("Najmodavac.Models.TipSmjestaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NazivSmjestajaFk")
                        .HasColumnType("int");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("NazivSmjestajaFk");

                    b.ToTable("TipoviSmjestaja");
                });

            modelBuilder.Entity("Najmodavac.Models.ViewModel.NazivViewTipSmjestaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TipSmjestajaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipSmjestajaId");

                    b.ToTable("NazivViewTipSmjestaja");
                });

            modelBuilder.Entity("Najmodavac.Models.NazivSmjestaja", b =>
                {
                    b.HasOne("Najmodavac.Models.ViewModel.NazivViewTipSmjestaja", null)
                        .WithMany("NazivSmjestaja")
                        .HasForeignKey("NazivViewTipSmjestajaId");
                });

            modelBuilder.Entity("Najmodavac.Models.TipSmjestaja", b =>
                {
                    b.HasOne("Najmodavac.Models.NazivSmjestaja", "NazivSmjestaja")
                        .WithMany()
                        .HasForeignKey("NazivSmjestajaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Najmodavac.Models.ViewModel.NazivViewTipSmjestaja", b =>
                {
                    b.HasOne("Najmodavac.Models.TipSmjestaja", "TipSmjestaja")
                        .WithMany()
                        .HasForeignKey("TipSmjestajaId");
                });
#pragma warning restore 612, 618
        }
    }
}
